export enum GEMS {
    STREAK_RESTORE,     // g00
    DROP_BOOST,         // gb0
    HIGH_DROP_BOOST,    // gb1
    MYSTERY_GEM,        // g01
    DAILY_DOUBLE_CLAIM  // g02
}

export enum ITEMS {
    RANDOM_DROP_COMMON,
    RANDOM_DROP_RARE,
    RANDOM_DROP_RAREST,
    WEIGHTED_COIN_ONE_USE,
    WEIGHTED_COIN_THREE_USE,
    GEM_SHARD,
    SHOP_VOUCHER,
    LOT_SCRATCH,
}

export enum CUSTOMIZATION_UNLOCKS {
    COIN_DEF,
    COIN_RED,
    COIN_GREEN,
    COIN_BLUE,
    COIN_PINK,
    COIN_PURPLE,
    CV_LEVEL_THEME_DEF,
    CV_LEVEL_THEME_RED,
    CV_LEVEL_THEME_GREEN,
    CV_LEVEL_THEME_BLUE,
    CV_LEVEL_THEME_PINK,
    CV_LEVEL_THEME_PURPLE,
    STR_COINFLIP,
    STR_OKASH,
    SYS_BANK_ACCESS,
    SYS_LOAN_ACCESS
}

export enum ITEM_TYPE {
    ITEM,
    GEM,
    CUSTOMIZATION
}